name: hexcolorname_example
description: Demonstrates how to use the hexcolorname plugin.
publish_to: none

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolorname:
    path: "../"
  flutter_colorpicker:

flutter:
  uses-material-design: true
